version: '4.44.2'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=openpg
      - POSTGRES_PASSWORD=openpgpwd
    ports:
      - "5432:5432"

  odoo:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=openpg
      - PASSWORD=openpgpwd